# Generated by Django 2.0.4 on 2018-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eyw_transactionref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
