# Generated by Django 2.0.4 on 2018-04-05 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_user_eyw_transactionref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='eyw_transactionref',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
